### ISSUE TITLE
[PkgEval] DistributedArrays may have a testing issue on Julia 0.4 (2015-03-06)

### ISSUE THREAD

**Issue by IainNZ** [JuliaParallel/DistributedArrays.jl#1]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.

#### On Julia 0.4
* On **2015-03-06** the testing status was `N/A - new package.`
* On **2015-03-06** the testing status changed to `Tests fail, but package loads.`

`Tests fail, but package loads.` means that PackageEvaluator found the tests for your package, executed them, and they didn't pass. However, trying to load your package with `using` worked.

*This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added.*

*Test log*:
```
>>> 'Pkg.add("DistributedArrays")' log
INFO: Cloning cache of DistributedArrays from git://github.com/JuliaParallel/DistributedArrays.jl.git
INFO: Installing DistributedArrays v0.1.0
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of DistributedArrays
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'using DistributedArrays' log
Julia Version 0.4.0-dev+3685
Commit e190f8c (2015-03-06 13:30 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
/home/vagrant/testpkg/v0.4/DistributedArrays

>>> test log
WARNING: Module DistributedArrays not defined on process 2
fatal error on 2: ERROR: UndefVarError: DistributedArrays not defined
 in deserialize at serialize.jl:378
 in handle_deserialize at serialize.jl:353
 in deserialize at serialize.jl:418
 in handle_deserialize at serialize.jl:353
 in deserialize at serialize.jl:407
 in handle_deserialize at serialize.jl:353
 in anonymous at task.jl:820
ERROR: LoadError: LoadError: ArgumentError: stream is closed or unusable
 in check_open at stream.jl:299
 in uv_write at stream.jl:736
 in flush at stream.jl:790
 in anonymous at multi.jl:179
 in lock at stream.jl:812
 in send_msg_ at ./multi.jl:170
 in remotecall at multi.jl:649
 in copy! at /home/vagrant/testpkg/v0.4/DistributedArrays/src/DistributedArrays.jl:342
 in copy at abstractarray.jl:300
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:249
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:321
 in _start at ./client.jl:413
while loading /home/vagrant/testpkg/v0.4/DistributedArrays/test/darray.jl, in expression starting on line 9
while loading /home/vagrant/testpkg/v0.4/DistributedArrays/test/runtests.jl, in expression starting on line 9
ArgumentError("stream is closed or unusable")

INFO: Testing DistributedArrays
==========================[ ERROR: DistributedArrays ]==========================

failed process: Process(`/home/vagrant/julia04/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/testpkg/v0.4/DistributedArrays/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: DistributedArrays had test errors
 in error at error.jl:19
 in test at pkg/entry.jl:717
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:69
 in process_options at ./client.jl:295
 in _start at ./client.jl:413


>>> end of log
```

**Comment by IainNZ** [comment]
Wasn't sure if this was a known problem

**Comment by jakebolewski** [comment]
Weird, it seems like worker process is not loading  the package.  Do you have the evaluator script somewhere?  How are you launching the parallel processes?

**Comment by IainNZ** [comment]
Everything is in the README at https://github.com/IainNZ/PackageEvaluator.jl, but essentially it is getting launched with

```julia
pkg_name = "DistributedArrays"
juliapkg = "somenondefaultlocation"
pkg_test = "Pkg.test(\"$(pkg_name)\")" :
pkg_test = "ENV[\"JULIA_PKGDIR\"] = \"$(juliapkg)\"; " * pkg_test
julia -e `$pkg_test`
```

and I'm guessing the children aren't looking in `juliapkg` because that won't be passed on to them...

**Comment by IainNZ** [comment]
I don't have an up-to-date v0.4 to test with, but I wonder would even

```julia
JULIA_PKGDIR=/some/location julia -e 'Pkg.test("DistrubtedArrays")'
```

work?

**Comment by IainNZ** [comment]
(if so, thats an argument I should re-organize things)

**Comment by jakebolewski** [comment]
`PKG_DIR` has to be defined outside the julia process, so that change would work. A changed `ENV` of the master process does not propagate to other spun up processes.

**Comment by IainNZ** [comment]
Yeah makes sense
