### ISSUE TITLE
DArray conversion uses 3x memory

### ISSUE THREAD

**Issue by denizyuret** [JuliaParallel/DistributedArrays.jl#11]
When I distribute a large local array, or convert a distributed one to local, I notice that the memory taken up is 3x the original array size, not 2x as one would hope.  Is there any way around this?

**Comment by amitmurthy** [comment]
I think the underlying issue is the same one as https://github.com/JuliaLang/julia/issues/8912

**Comment by jakebolewski** [comment]
What is the status here now that #6597 is closed?

**Comment by amitmurthy** [comment]
There is no leak, i.e.,

```
for i in 1:100
         d=dones(2*10^8)
         a=convert(Array,d)
         @everywhere gc()
       end
```

executes without any issues now that #6597 is closed. However the resident memory does go up after the first few iterations and does not come down. 

I think it may be an issue with buffers being cached for reuse and not being released to the system. That would be an issue with Julia Base, and not with this package.

**Comment by jakebolewski** [comment]
Ok, I'll close this issue then.
