### ISSUE TITLE
ERROR: UndefVarError: SPMD not defined

### ISSUE THREAD

**Issue by pancetta** [JuliaParallel/DistributedArrays.jl#129]
I got a clean installation of Julia 0.5.0 on my Mac (macOS Sierra) and `Pkg.add("DistributedArrays")` works nicely. However, when I do `@everywhere importall DistributedArrays.SPMD`, I get this: 

```
ERROR: UndefVarError: SPMD not defined
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in #1 at ./multi.jl:1957 [inlined]
 in run_work_thunk(::##1#3, ::Bool) at ./multi.jl:1001
 in #remotecall_fetch#605 at ./multi.jl:1055 [inlined]
 in remotecall_fetch(::Function, ::Base.LocalProcess) at ./multi.jl:1055
 in #remotecall_fetch#609(::Array{Any,1}, ::Function, ::Function, ::Int64) at ./multi.jl:1080
 in remotecall_fetch(::Function, ::Int64) at ./multi.jl:1080
 in (::##2#4)() at ./multi.jl:1959
 in #remotecall_fetch#605 at ./multi.jl:1056 [inlined]
 in remotecall_fetch(::Function, ::Base.LocalProcess) at ./multi.jl:1055
 in #remotecall_fetch#609(::Array{Any,1}, ::Function, ::Function, ::Int64) at ./multi.jl:1080
 in remotecall_fetch(::Function, ::Int64) at ./multi.jl:1080
 in (::##2#4)() at ./multi.jl:1959
 in sync_end() at ./task.jl:311
 in macro expansion; at ./multi.jl:1968 [inlined]
 in anonymous at ./<missing>:?
```

What am I missing here?

**Comment by andreasnoack** [comment]
The problem is that the SPMD mode was added after the most recent release of the package. Consequently, the SPMD mode is only available on the master branch of the package. The master branch requires the development version of Julia though. It should be possible to tag a release for Julia 0.5 which includes SPMD if you don't want to wait for the release of Julia 0.6.

**Comment by pancetta** [comment]
Thanks for your quick reply. I didn't look at the sources of the recent release, only at the master. Sorry for that. Anyway, I'd love to see this working with Julia 0.5. Yet, if Julia's roadmap is accurate, the 0.6 release might not be this far away and I'm fine with waiting a few weeks.
