### ISSUE TITLE
Distributed generated of a DArray

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaParallel/DistributedArrays.jl#145]
I have generated arrays on separate processes, and cannot collect them into a single array on the master process because it cannot fit into memory. Is there a way to directly generate the `DArray` without having to put it on the master process?

**Comment by andreasnoack** [comment]
Yes, but please ask questions on discourse.

**Comment by ChrisRackauckas** [comment]
Sorry, wasn't sure if it was already a part of the functionality since I didn't see a constructor for it and `dfill` just stalled, so I thought it was a feature request / help making a PR. I'll take it to Discourse.
