### ISSUE TITLE
Unintuitive/Inconsistent Distribution for Uneven Grids

### ISSUE THREAD

**Issue by JosephTomlinson** [JuliaParallel/DistributedArrays.jl#166]
The distribution behavior for uneven grids is unintuitive/inconsistent and makes working with `DArray`s more challenging then it needs to be when dealing with inter-process communication.

For example a length 7 `DArray` split into three processes produces the distribution 2,3,2
That same length `DArray` split into four processes produces 2,1,2,2
This makes any code involving transmitting blocks between processes challenging to write as from what I can tell there is no way for each process to identify which other processes have more data without going through additional communication.

I believe the intuitive behavior should be to have the lower indices contain the additional elements.
If this is a non-trivial change I am willing to code it myself but would appreciate someone familiar with the internals pointing me in the right direction.

**Comment by andreasnoack** [comment]
I support this change. I remember having to deal with that long time ago when trying to wrap ScaLAPACK, https://github.com/JuliaParallel/ScaLAPACK.jl/blob/9451aa67d58351b81ff22e542ef95ab19436a8fb/src/ScaLAPACK.jl
