### ISSUE TITLE
Load Files Into Portions of Arrays

### ISSUE THREAD

**Issue by r-barnes** [JuliaParallel/DistributedArrays.jl#176]
I have a large number of matrices stored to disk on a distributed system. Together, they represent a grid of data, like so:

    X X X X
    X X X X
    X X X X 

where each `X` is a matrix contained in a different file.

Eventually, I'll do focal operations which will require transmitting data at the borders of these matrices between machines. DistributedArrays seems like a good way of doing this.

But it's unclear whether it's possible to force distributed arrays to break the data apart into an `m x n` grid where the portion of the distributed array allotted to each processor is guaranteed to be a specified size. (More generally, the particular size could vary between processes as long as each entry of a given row and each entry of a given column of the grid had the same shape.)

Is there a way to induce and enforce this behavior?

Perhaps a constructor could be added?

**Comment by vchuravy** [comment]
You probably want to use this constructor: https://github.com/JuliaParallel/DistributedArrays.jl/blob/85243f0ddb20f925b7248f9add04ba2d3c45b646/src/darray.jl#L186

An example usage is described here: https://github.com/JuliaParallel/DistributedArrays.jl/blob/85243f0ddb20f925b7248f9add04ba2d3c45b646/test/darray.jl#L293-L297

**Comment by r-barnes** [comment]
Thanks! The links you sent were a little confusing due to the use of `sprand`, but I was able to figure it out with some more digging based on the keywords. Here's some potentially cleaner examples:

```
@everywhere using Distributed
@everywhere using DistributedArrays

r1 = DistributedArrays.remotecall(() -> rand(10,10), workers()[1]) 
r2 = DistributedArrays.remotecall(() -> rand(10,10), workers()[2]) 
r3 = DistributedArrays.remotecall(() -> rand(10,10), workers()[3]) 
r4 = DistributedArrays.remotecall(() -> rand(10,10), workers()[4]) 
D = DArray(reshape([r1 r2 r3 r4], (2,2))) 
[@fetchfrom p localindices(D) for p in workers()]

N   = 30
ras = [@spawnat p rand(30,30) for p in workers()[1:4]]
ras = reshape(ras,(2,2))
D   = DArray(ras)
[@fetchfrom p localindices(D) for p in workers()]
```

Follow up question: if I understand the code your link to, DistributedArrays also works on sparse arrays?

**Comment by vchuravy** [comment]
Yes in theory you can use any chunk type which includes sparse arrays, I can't promise you that we do smart things with it though ;)
