### ISSUE TITLE
Stable documentation link is broken

### ISSUE THREAD

**Issue by cossio** [JuliaParallel/DistributedArrays.jl#193]

**Comment by r-barnes** [comment]
The development link works.

**Comment by jonathanBieler** [comment]
How does the doc for different versions are generated ? Some packages have a lot of version available.

**Comment by vchuravy** [comment]
As part of CI https://travis-ci.org/JuliaParallel/DistributedArrays.jl/jobs/527523577

It seems that CI for the tag needs to succeed so that stable version is build.

**Comment by vchuravy** [comment]
Should be fixed now! Turned out it was a misconfiguration of CI
