### ISSUE TITLE
Compatible with Primes v0.5.0?

### ISSUE THREAD

**Issue by GregPlowman** [JuliaParallel/DistributedArrays.jl#222]
Can `DistributedArrays` use `Primes v0.5.0`?

**Comment by HetaoZ** [comment]
If you are trying to add `DistributedArrays` in the local machine, you may encounter a compiling problem of `Primes v0.4.0` which lacks `Project.toml'. I have a revised version of `Primes v0.4.0`that can solve this problem. The link: https://github.com/HetaoZ/Primes.jl

**Comment by andreasnoack** [comment]
Would be great if you could look into why https://github.com/JuliaParallel/DistributedArrays.jl/pull/225 is failing

**Comment by andreasnoack** [comment]
Closed by #232
