### ISSUE TITLE
DistributedArrays and Krylov libraries

### ISSUE THREAD

**Issue by FredericN** [JuliaParallel/DistributedArrays.jl#231]
I want to use a Krylov package with a distributed matrix. I thought it would be very easy since DistributedArrays define the mat vec product and the scalar product. Unfortunately, with the packages I have tried, I have compiler errors. My question is: are you aware of a Krylov library that is compatible with DistributedArrays?

**Comment by andreasnoack** [comment]
Hello Frederic,

Such questions are better suited for discourse.julialang.org. The issue tracker is mostly for bug reports and feature discussions.
