### ISSUE TITLE
distribute is not type inferrable

### ISSUE THREAD

**Issue by mohamed82008** [JuliaParallel/DistributedArrays.jl#235]
The following function doesn't infer properly:
```julia
using DistributedArrays
addprocs(1)
@code_warntype DistributedArrays.distribute(rand(10), procs = [1,2])
```

**Comment by andreasnoack** [comment]
I'd think that it's been that assumption here that type stability doesn't really matter compared to the overhead from sending data to other processes. Do you have a use case where you think it would matter?

**Comment by mohamed82008** [comment]
probably won't matter in my case, closing this issue.
