### ISSUE TITLE
Distributed floating point operations have different numeric behavior compared to Base methods

### ISSUE THREAD

**Issue by jakebolewski** [JuliaParallel/DistributedArrays.jl#3]
Floating point operations like `sum` are order dependent, there are subtle numeric differences when performing operations on distributed chunks and then reducing the result.  The numeric result will differ in how we decide to perform the operations, the order in which we perform the final reduction (async or fully sync final reduction), and the different ways we want to look into layout of the local parts of the distributed array.

I don't know what we really can do here, but this is definitely a gotcha that users need to be aware of.

cc @andreasnoack, @jiahao

**Comment by ViralBShah** [comment]
Just goes in the documentation.
