### ISSUE TITLE
mapslices

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/DistributedArrays.jl#32]
@andreasnoack I recollect discussing that we did have some `mapslices` implementation, and also something like Star-P's `ppeval`. Could you check them in? I would be ok with having a name such as `mapslices_n` to denote n inputs - and perhaps renaming to something better when we have it.

**Comment by jakebolewski** [comment]
@ViralBShah what is the difference between `ppeval` and parallel `map`?

**Comment by andreasnoack** [comment]
@jakebolewski `ppeval` is like `mapslices`, i.e. applies the function along a dimension of the array(s). The version I've written specifies the dimensions differently from `mapslices` in a way that allows for broadcasting behavior.

**Comment by andreasnoack** [comment]
@ViralBShah See #34

**Comment by andreasnoack** [comment]
#34 is merged
