### ISSUE TITLE
warning in julia v0.4

### ISSUE THREAD

**Issue by denizyuret** [JuliaParallel/DistributedArrays.jl#36]
The following warning is generated each time DistributedArrays is loaded in Julia v0.4:

Warning: Method definition getindex(Base.RemoteRef, Any...) in module Base at multi.jl:1642 
overwritten in module DistributedArrays at /home/nlg-05/dy_052/kuparser/profile/v0.4/DistributedArrays/src/DistributedArrays.jl:403.

**Comment by andreasnoack** [comment]
I've tagged a new version which should fix this.
