### ISSUE TITLE
test suite failing on 0.5 julia master

### ISSUE THREAD

**Issue by amitmurthy** [JuliaParallel/DistributedArrays.jl#46]
The test suite is failing for me on julia master
```
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+1030 (2015-10-30 11:53 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit ee584e8* (0 days old master)
|__/                   |  x86_64-apple-darwin14.5.0

```

output - https://gist.github.com/amitmurthy/20c9d263f1dc95e26323

Anybody else seeing this?

**Comment by amitmurthy** [comment]
cc: @andreasnoack

**Comment by andreasnoack** [comment]
This must be because of some changes in base. There have been changes to reductions as well as the parallel stuff. I'll take a look.

**Comment by amitmurthy** [comment]
One thing I noticed was that the mapreduce tests overflow 64 bit ints. Somehow it was working all this while, but now multiple overflows in the distributed case is causing them to fail. Haven't looked at the other errors.

**Comment by amitmurthy** [comment]
With `_mapreduce` changed to :
```
function _mapreduce(f, opt, d::DArray)
    println("$opt")
    v = Any[fetch(r) for r in Any[ @spawnat p (println(opt);mapreduce(f, opt, localpart(d))) for p in procs(d) ]]
    reduce(opt, v)
end
```

The first debug print is the correct one - `Base.AddFun()` or `Base.MulFun()` as the case may be in the test suite, but the second one (printed on the worker) is always `Base.AddFun()`.  Don't have an explanation for this.

cc: @vtjnash - any changes recently that could cause this?
