### ISSUE TITLE
array distribution type

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/DistributedArrays.jl#5]
I feel that we really should have array distribution as a type, on which we dispatch. That way, instead of `dones`, we would be able to do `ones(RowDist, eltype, m, n)` for example. Having distribution types will also allow us to cleanly support different layouts.

**Comment by jakebolewski** [comment]
I like the design of Chapel's domain maps.  We have a greater ability to experiment here as user defined domain maps are difficult to implement in Chapel.  I feel it will take a lot of experimentation to come up with a design that works well and generalizes beyond dense arrays.

**Comment by ViralBShah** [comment]
Yeah - that would be quite cool. My Star-P experience suggested that having support for a few dense distributions and one sparse distribution took us a long way. The GlobalArrays is another framework to look at.

http://hpc.pnl.gov/globalarrays/
