### ISSUE TITLE
drandn sometimes crashes

### ISSUE THREAD

**Issue by AntonioSuriano** [JuliaParallel/DistributedArrays.jl#50]
Windows 32 bit.
Julia 0.4.1
on Windows 8.1 64bit  and Windows 10 64 bit (different machines).

it happens more often if the number of cycles is larger...
it seems not to depend on the number of procs (I tried also 20).
code:

```jl
addprocs(3)

@everywhere using DistributedArrays

function tony(N)
return sum(drandn(N,N))
end


function pesante(N)
a=zeros(N,N)
for i = 1:N
for j=1:N
a[i,j]=tony(1000)
end
end
return a
end

matrice= pesante(100)

```
----
julia 0.4.1

when calling pesante with `N>30` sometimes it crashes
```jl
LoadError: BoundsError: attempt to access 0-element Array{Any,1}
  at index [2]
while loading In[3], in expression starting on line 20

fatal error on 2: ERROR: MethodError: `convert` has no method matching convert(::Type{RemoteRef{T<:AbstractChannel}}, ::Base.RemoteDoMsg)
This may have arisen from a call to the constructor RemoteRef{T<:AbstractChannel}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, !Matched::T)
  RemoteRef()
  ...
 in setindex! at array.jl:313
 in deserialize_array at serialize.jl:616
 in deserialize_datatype at serialize.jl:651
 in handle_deserialize at serialize.jl:477 (repeats 2 times)
 in deserialize_datatype at serialize.jl:651
 in message_handler_loop at multi.jl:861
 in anonymous at task.jl:63
Worker 2 terminated.
ERROR (unhandled task failure): EOFError: read end of file
 in read at stream.jl:911
 in message_handler_loop at multi.jl:861
 in anonymous at task.jl:63
```

**Comment by andreasnoack** [comment]
@amitmurthy Do you have any idea about what is happening here?

**Comment by jakebolewski** [comment]
This is most likely https://github.com/JuliaLang/julia/commit/312e65c8e60a4c58c92db7845dba8d397eeb00b6.   @AntonioSuriano what version of Julia are you using, v0.4.1 or the latest master?

**Comment by AntonioSuriano** [comment]
0.4.1 official

**Comment by amitmurthy** [comment]
I don't think it is https://github.com/JuliaLang/julia/commit/312e65c8e60a4c58c92db7845dba8d397eeb00b6

since there are no multiple writers doing a concurrent `put!`. This looks like a deserialization error specifically on Windows.

I ran quite a few iterations on Linux without any issues. Can you try something like this?

```
addprocs(3)

using DistributedArrays

function tony(N)
  return sum(drandn(N,N))
end


function pesante(N)
    a=zeros(N,N)
    for i = 1:N
        for j=1:N
            a[i,j]=tony(1000)
            println("$i $j")
        end
    end
    
    @everywhere Base.flush_gc_msgs()
    @everywhere gc()
    
    return a
end

matrice= pesante(1000)

```

i.e., remove the `@everywhere` from `using` and add 
```
    @everywhere Base.flush_gc_msgs()
    @everywhere gc()
```

The above two lines force a distributed gc. Without them, I would see a segfault due to running out of memory.

**Comment by andreasnoack** [comment]
Please comment if this is still an issue
