### ISSUE TITLE
convert(Array, a::DArray) doesn't work for me.

### ISSUE THREAD

**Issue by michaellindon** [JuliaParallel/DistributedArrays.jl#59]
When I convert an Array to a DArray, I cannot seem to convert back, and I do not understand the error message. Here's what happens

```
julia> Btrials=@DArray [trial for trial in Btrials];
julia> localB=convert(Array,Btrials)
ERROR: On worker 2:
UndefVarError: Btrials not defined
 [inlined code] from /home/grad/msl33/.julia/v0.4/DistributedArrays/src/DistributedArrays.jl:136
 in anonymous at no file:0
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:645
 in run_work_thunk at multi.jl:654
 in anonymous at task.jl:58
 in remotecall_fetch at multi.jl:731
 in call_on_owner at multi.jl:776
 in fetch at multi.jl:784
 in chunk at /home/grad/msl33/.julia/v0.4/DistributedArrays/src/DistributedArrays.jl:257
 in anonymous at task.jl:447

...and 5 other exceptions.

 in sync_end at ./task.jl:413
 [inlined code] from task.jl:422
 in convert at /home/grad/msl33/.julia/v0.4/DistributedArrays/src/DistributedArrays.jl:344
 in convert at abstractarray.jl:421

```

Btrials is an Array of element type Btrial, a composite type that I have defined.

Can anyone shed any light on this?

**Comment by andreasnoack** [comment]
Please provide a self-contained example? Converting to `Array` works fine for me.

**Comment by michaellindon** [comment]
Please try the following:

`using DistributedArrays                                                                                                                                                                                            
                                                                                                                                                                                                                   
@everywhere type Atrial                                                                                                                                                                                            
        id::Int64                                                                                                                                                                                                  
        Tobs::Float64                                                                                                                                                                                              
        y₀::Dict                                                                                                                                                                                                   
        ξ₀ₐ::Dict                                                                                                                                                                                                  
        ξ₀ᵣ::Dict                                                                                                                                                                                                  
end                                                                                                                                                                                                                
                                                                                                                                                                                                                   
@everywhere function Atrial(id,ξ₀ₐ,Tobs)                                                                                                                                                                           
        return Atrial(id,Tobs,Dict(),ξ₀ₐ,Dict())                                                                                                                                                                   
end                                                                                                                                                                                                                
                                                                                                                                                                                                                   
Atrials=[Atrial(i,Dict(zip(rand(10),rand(10)),),1) for i=1:10];                                                                                                                                                    
DAtrials=@DArray [trial for trial in Atrials];                                                                                                                                                                     
LAtrials=convert(Array,DAtrials);`

Copying from my Repl:

`
[msl33@cabbage pprocess]$ julia -p 8
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-rc3 (2015-09-27 20:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-unknown-linux-gnu

julia> using DistributedArrays

julia> @everywhere type Atrial
           id::Int64
           Tobs::Float64
           y₀::Dict
           ξ₀ₐ::Dict
           ξ₀ᵣ::Dict
       end

julia> 

julia> @everywhere function Atrial(id,ξ₀ₐ,Tobs) 
           return Atrial(id,Tobs,Dict(),ξ₀ₐ,Dict())
       end
julia> Atrials=[Atrial(i,Dict(zip(rand(10),rand(10)),),1) for i=1:10];

julia> DAtrials=@DArray [trial for trial in Atrials];

julia> LAtrials=convert(Array,DAtrials);
ERROR: On worker 2:
UndefVarError: Atrials not defined
 [inlined code] from /home/grad/msl33/.julia/v0.4/DistributedArrays/src/DistributedArrays.jl:136
 in anonymous at no file:0
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:645
 in run_work_thunk at multi.jl:654
 in anonymous at task.jl:58
 in remotecall_fetch at multi.jl:731
 in call_on_owner at multi.jl:776
 in fetch at multi.jl:784
 in chunk at /home/grad/msl33/.julia/v0.4/DistributedArrays/src/DistributedArrays.jl:257
 in anonymous at task.jl:447

...and 7 other exceptions.
 in sync_end at ./task.jl:413
 [inlined code] from task.jl:422
 in convert at /home/grad/msl33/.julia/v0.4/DistributedArrays/src/DistributedArrays.jl:344
 in convert at abstractarray.jl:421


`

**Comment by andreasnoack** [comment]
The error is in the line before, i.e.
```jl
julia> DAtrials=@DArray [trial for trial in Atrials];
```
It's a little tricky macro thing, but because the expressions are executed at the top level the variable `Atrials` is global and therefore not being distributed to the workers. Only local variables are sent, so a solution is to wrap that step in a small function, i.e.
```jl
julia> f(x) = @DArray [trial for trial in x]
f (generic function with 1 method)
```
and then
```jl
julia> DAtrials = f(Atrials);

julia> convert(Array, DAtrials)
10-element Array{Atrial,1}:
 Atrial(1,1.0,Dict{Any,Any}(),Dict(0.037763773839299075=>0.84711
5605=>0.31049171000164444,0.730385635441511=>0.9545034361044258,...
```

**Comment by michaellindon** [comment]
Ah, thank you for clarifying this :) I found it neater in the end to write

`
DAtrials=distribute(Atrials)
`

Can I just clarify, the correct way to write a parallel for loop would look like this:

`@sync @parallel for trial in Atrials                                                                                                                                                                               
        fillme!(trial)                                                                                                                                                                                             
end`

**Comment by michaellindon** [comment]
It seems I don't really understand how this works. Here is an example:

```
using DistributedArrays

Atrials=[zeros(Float64,1000000) for i=1:10];
Atrials=distribute(Atrials)

@everywhere function fillme!(trial)
	for i=1:length(trial)
		trial[i]=trial[i]+1
	end
end

@time for i=1:100
	@sync @parallel for trial in Atrials
		fillme!(trial)
	end
end


loc=convert(Array,Atrials)
```

```
julia> loc
10-element Array{Array{Float64,1},1}:
 [100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0  …  100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0]
 [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0  …  0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]                                        
 [100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0  …  100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0]
 [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0  …  0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]                                        
 [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0  …  0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]                                        
 [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0  …  0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]                                        
 [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0  …  0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]                                        
 [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0  …  0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]                                        
 [100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0  …  100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0]
 [100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0  …  100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0]
```

It looks like it hasn't worked for some of them
