### ISSUE TITLE
Transpose is very slow

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/DistributedArrays.jl#65]
On julia 0.5 and tagged version of the package, this goes into an infinite loop:
````
julia> x = dones(5000,5000);
julia> @time x';
````

**Comment by jiahao** [comment]
I can't reproduce this bug. I'm running DistributedArrays v0.2.0 on Julia 0.5.0-dev+3928
Commit `fdc4a85` (2016-05-06 04:46 UTC) on Linux.

**Comment by andreasnoack** [comment]
@ViralBShah I also don't see this. Do you still have this issue?

**Comment by ViralBShah** [comment]
Can't see it on the latest master.

**Comment by ViralBShah** [comment]
I see the issue. Even with one processor on Julia 0.4 on my mac, it is very slow:

````
julia> a = drand(1000,1000);

julia> @time a';
  6.344167 seconds (40.76 M allocations: 1.010 GB, 2.48% gc time)
````

**Comment by amitmurthy** [comment]
I don't see this issue on master now.

**Comment by andreasnoack** [comment]
I don't see this either. Please reopen or comment if you see it again.
