### ISSUE TITLE
ERROR: factor(4,) has been moved to the package Primes.jl. 

### ISSUE THREAD

**Issue by musmo** [JuliaParallel/DistributedArrays.jl#73]
Trying to follow Andreas's parallel workshop notebooks
However,
```julia
julia> D = distribute(C)
ERROR: factor(4,) has been moved to the package Primes.jl.
Run Pkg.add("Primes") to install Primes on Julia v0.5-
 in factor(::Int64, ::Vararg{Int64,N}) at .\deprecated.jl:210
 in defaultdist(::Tuple{Int64}, ::Array{Int64,1}) at C:\Users\mus\.julia\v0.5\DistributedArrays\src\DistributedArrays.jl:320
 in distribute(::Array{Int64,1}) at C:\Users\mus\.julia\v0.5\DistributedArrays\src\DistributedArrays.jl:492
 in eval(::Module, ::Any) at .\boot.jl:234
 in macro expansion at .\REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at .\event.jl:46
```

**Comment by andreasnoack** [comment]
Have you tried to follow the recommendation in the error message? 

I cannot recommend using 0.5 with `DistributedArrays.jl` yet.

**Comment by musmo** [comment]
Yes I have tried `Pkg.add("Primes"); using Primes`. Fair enough, will use 0.4 for the tutorials

**Comment by andreasnoack** [comment]
It should work. Did you restart Julia?

**Comment by musmo** [comment]
Ah of course. Thank you.

**Comment by dpo** [comment]
Sorry if the question sounds stupid but why is it necessary to `Pkg.add("Primes")` if [`Primes` is listed in `REQUIRE`](https://github.com/JuliaParallel/DistributedArrays.jl/blob/master/REQUIRE#L3)?

**Comment by andreasnoack** [comment]
I think it is because `DistributedArrays` was already installed when the dependency was added. For at new install of the package, it shouldn't be necessary. Ideally, I think the package manager should install new dependencies on upgrades and I don't know why it's not doing that.

**Comment by dpo** [comment]
Thanks. At least on Travis, [`Primes` isn't being installed](https://travis-ci.org/JuliaSmoothOptimizers/Krylov.jl/jobs/146910645#L188).

**Comment by andreasnoack** [comment]
Ah. Thanks for pointing this out. We need to tag a new version.

**Comment by dpo** [comment]
Any eta for when that might happen?

**Comment by andreasnoack** [comment]
Sorry for the delay. See https://github.com/JuliaLang/METADATA.jl/pull/5907/files

**Comment by dpo** [comment]
Great, thank you!

**Comment by manauwar1212** [comment]
just use (using Primes and below import Primes:isprime,primes,primesmask,factor)
