### ISSUE TITLE
sum distributed array  on cluster very very slow

### ISSUE THREAD

**Issue by armgong** [JuliaParallel/DistributedArrays.jl#8]
following code very very slow on sum(DA), it takes ten minutes and still no result,so I interrupted it use ctrl+c.
this shouldn't  happens if DistributedArrays  operations are performed over the localpart chunks and then aggregated. maybe there are some issues? 
~~~julia
 x=Array(ASCIIString,6)
 x[1]="arch01"
 x[2]="arch02"
 x[3]="arch03"
 x[4]="arch04"
 x[5]="arch05"
 x[6]="arch06"
addprocs(x)
@everywhere using DistributedArrays
A = fill(1.1, (1000,1000));
sum(A)
DA = distribute(A);
sum(DA)
sum(A) == sum(DA)

**Comment by amitmurthy** [comment]
Most of the standard functions are yet to be written to support DArrays. The generic `sum` is currently fetching elements of the DArray onto the calling process one-by-one and summing locally.

At least for the functions that operate on Arrays - `sum`, `minimum`, `maximum`, etc. the corresponding DArray versions could be generated with the implementation using a distributed `map` ?

**Comment by ViralBShah** [comment]
:+1:

**Comment by armgong** [comment]
thank you very much
