### ISSUE TITLE
Track performance regressions.Implement set of benchmarks.

### ISSUE THREAD

**Issue by amitmurthy** [JuliaParallel/DistributedArrays.jl#89]
Looking at a few other packages I noticed a 10-15% slowdown between 0.4 and master. However, DistributedArrays is showing a slowdown for the entire test suite run of around 20-30%. The underlying causes for this may very well be in Base. This issue has been created to help track down specific instances of slowdown so that they may be addressed better in Base.

**Comment by vchuravy** [comment]
Are these actual performance regression or is this the penalty coming in from longer compile times + closures? We should probably come up with a set of benchmarks that we can test with `BenchmarkTools`

**Comment by amitmurthy** [comment]
Anecdotal at this point. Considering longer compile times are the same across packages and that closures have been optimized in 0.5, comparing, for example, PR histories of `DataFrames` and `ProtoBuf`, they have seen a slowdown of approx. 10% while it is considerably more here.
